### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by mmulich** [openstax/setup-openstax-machine#12]
The installation is missing instructions for installing libmagic.

```pytb
Traceback (most recent call last):
  File "/Users/pumazi/cnx/src/nebuchadnezzar/.venv/bin/neb", line 11, in <module>
    load_entry_point('nebuchadnezzar', 'console_scripts', 'neb')()
  File "/Users/pumazi/cnx/src/nebuchadnezzar/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/pumazi/cnx/src/nebuchadnezzar/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Users/pumazi/cnx/src/nebuchadnezzar/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Users/pumazi/cnx/src/nebuchadnezzar/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/pumazi/cnx/src/nebuchadnezzar/nebu/cli/main.py", line 13, in <module>
    from .publish import publish
  File "/Users/pumazi/cnx/src/nebuchadnezzar/nebu/cli/publish.py", line 10, in <module>
    from litezip import (
  File "/Users/pumazi/cnx/src/nebuchadnezzar/.venv/lib/python3.7/site-packages/litezip/__init__.py", line 3, in <module>
    from .main import *
  File "/Users/pumazi/cnx/src/nebuchadnezzar/.venv/lib/python3.7/site-packages/litezip/main.py", line 3, in <module>
    import magic
  File "/Users/pumazi/cnx/src/nebuchadnezzar/.venv/lib/python3.7/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Comment by m1yag1** [comment]
oh that should be easy to install with brew.
